version: "3.8"

services:
  kasm-rpa-desktop:
    image: kasmweb/ubuntu-jammy-desktop:1.18.0
    container_name: kasm-rpa-desktop
    shm_size: 512m
    ports:
      - "6901:6901"
    environment:
      - VNC_PW=password
    restart: always
    volumes:
      - .:/data
    working_dir: /data
